apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: hello-world
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            securityContext: {}

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: rmq-mgt
spec:
  host: rmq-mgt-rabbitmq.apps-crc.testing
  to:
    kind: Service
    name: hello-world
    weight: 100
  port:
    targetPort: management
  wildcardPolicy: None
